# filter represents a switch name and defaults to "" (i.e. unset).
# If filter is not set, accessor properties will return "" or {} (depending on the property).
# If filter is set but no matching switch is found, accessor properties will return "" or {} (depending on the property).
---
filter: "LE1"
