---
config:
  - fabric_name: SITE1
    switch_name: LE1
    switch_username: admin
    switch_password: mySwitchPassword
  - fabric_name: SITE1
    switch_name: SP1
    switch_username: admin
    switch_password: mySwitchPassword
  - fabric_name: SITE2
    switch_name: LE2
    switch_username: admin
    switch_password: mySwitchPassword
